### ISSUE TITLE
proxyAuth.json should be configurable

### ISSUE THREAD

**Issue by AlexGilleran** [TerriaJS/terriajs-server#1]
`proxyAuth.json` is referenced by `require('./proxyAuth.json')`, which made sense when this was part of nationalmap because it was reasonable to change local json files, but now that this is a separate npm module it needs to be configurable in the same manner as `config.json`.

**Comment by stevage** [comment]
TBH I don't know anything about `proxyauth.json`. What does it actually do? Where would it typically be? Are you requesting a `--proxyauth ../proxyauth.json` kind of command line arg?

**Comment by meh9** [comment]
It makes it possible for the TerriaJS proxy to access web services requiring HTTP Basic Auth, like the Landgate SLIP service.

It is basically a hash of a hostname to a Base64 encoded Basic Auth string, which is added to the proxied request. There is an example file:

https://github.com/TerriaJS/terriajs-server/blob/master/proxyAuth.json.example

**Comment by AlexGilleran** [comment]
So there's a bit of code that looks for a `--config` arg and if that isn't there then it tries `/wwwroot` and if there's no `config.json` there then it tries `__dirname`. There's nothing like that for `proxyAuth`, it's still trying to require directly from `./proxyAuth`.

Not requesting anything though, just made the issue for tracking purposes, I'm most of the way through fixing it already :).
