### ISSUE TITLE
Refactor for testing

### ISSUE THREAD

**Issue by kring** [TerriaJS/terriajs-server#20]
There's a lot of logic in `app.js` that is difficult to test because it's all wrapped up in the node clustering.  We should refactor this and write tests.

**Comment by stevage** [comment]
Can you elaborate on this? Not sure what you mean by "wrapped up in the node clustering". Example of something that's hard to test?

**Comment by stevage** [comment]
(Oh yeah, a little bit of context here: https://github.com/TerriaJS/terriajs-server/pull/18#issuecomment-224491914 )

**Comment by stevage** [comment]
Wait, you forgot to tell me to update CHANGES.md.

**Comment by kring** [comment]
Not necessary because there's no user-visible change.
